### ISSUE TITLE
Docker version of the dashboard

### ISSUE THREAD

**Issue by ab73863** [ajaysreedhar/kongdash#25]
Hi Ajay,

First of all good effort building this beautiful dashboard for Kong and contributing to the community.
Is there a dockerized version of the dashboard on your road map like PGBI version of Kong dashboard?

Regards
Arun

**Comment by rocketspacer** [comment]
Should be a simple Dockerfile with `node` and `npm start`. Just submit a PR my friend

**Comment by ajaysreedhar** [comment]
Hi, Thanks. There's no dockerized version as it is a stand-alone desktop application.

**Comment by AndreMiras** [comment]
I worked on one that runs from the binary.
Adapting it to build from source using npm should hopefully be easier using this base.
I'm using it on a Linux host, but macOS or Windows would certainly different since they don't have a built-in X11 server.
https://github.com/AndreMiras/dockerfiles/tree/develop/primate
